### PR TITLE
Referenceable Content List

### PR DESCRIPTION
**Pull request by rdasika**
#ADOPT-288

## Integrate reference content into docs

Add referenceable content on projects and ecosystem tooling to inspire developers and help them quickly go from 0 to 1.

### CODE REVIEW

**Review by PaulLeCam — APPROVED** [review]
LGTM, have you tried building/running it locally to see if mkdocs raises any warning?

**Comment by dazuck** [comment]
looks good. is it weird to call it "Referencable projects" externally? not sure why that strikes me but probably fine. 

is every project categorized right for how it's used today and can be referenced? e.g., is DoinGud doing dynamicNFTs now (the article is just about profiles)?

**Review by 3avi — APPROVED** [review]
lgtm

**Comment by JustinaPetr** [comment]
@rdasika I opened a small pull request for fixing a link for one of the referenced projects. It was not allowing me to build the docs otherwise.

Another small thing - could we make the included links clickable (demo and code sections)? At the moment, for me, all the links render as regular text. As a user, I'd find it much easier to go through the list of projects if I could just click on a link instead of having to copy and paste them.

**Comment by rdasika** [comment]
@dazuck good call on the naming, I changed it to "Highlighted Projects". I categorized projects mostly for how they're being used. DoinGud I think is an exception to that (not sure if they are fully using for dynamic NFTs yet, but the blog post is an excellent write up on that topic.

@JustinaPetr thank you for the comments! I edited the link as well as made it so that they all show up as URLs. Github editing and rendering of .md files shows them as URLs, so I missed that.

**Comment by Whoopsfr** [comment]
Good

**Pull request merged**
