### PR TITLE
CDB-2398 Document node status endpoint

### PR DESCRIPTION
**Pull request by PaulLeCam**
I also updated mkdocs and had to fix some issues related to it as part of the change, the main contents change is the added "Node status" section in the HTTP API page.

### CODE REVIEW

**Comment by 3avi** [comment]
@willex @dbcfd

**Comment by 3avi** [comment]
LGTM, Alex reviewing and merging in a moment. fyi @PaulLeCam - @dbcfd found your health check section helpful for wheel!

**Review by 3avi — APPROVED** [review]
LGTM 🚀

**Review by willex — APPROVED** [review]
LGTM!

**Pull request merged**
