### PR TITLE
Updated structure

### PR DESCRIPTION
**Pull request by PaulLeCam**
Changes so far:

- Add updated and new references pages from v2
- Add docs/advanced from v2 for links to standards (accounts/DIDs, IDX and stream types)
- Add docs/advanced/standards to learn/standards nav
- Remove Auth and StreamTypes from navbar
    - Still in progress: make sure all the removed pages have redirects
- Change links from auth and stream types to docs/advanced pages
    - Still in progress: in some cases it might be better to point to the reference pages directly

Current issues:

- ~I don't know where to put the 3ID [lifecycle](https://developers.ceramic.network/authentication/3id-did/lifecycle/), [security](https://developers.ceramic.network/authentication/3id-did/security/) and [3Box migration](https://developers.ceramic.network/authentication/3id-did/3box-migration/) pages, they don't seem to be a good fit for either the page describing the standard or the reference page? Ideally we could have a dedicated docsite for 3ID, but in the meantime shall we keep these pages as they are and add links from the standard page?~

### CODE REVIEW

**Comment by PaulLeCam** [comment]
I haven't checked all the links yet but there shouldn't be any broken link to docs pages, otherwise mkdocs would have warned about these.
I'd mostly like to merge these changes to avoid conflicts with other changes to contents being done in parallel.

**Comment by PaulLeCam** [comment]
Yes it's just a first step into getting all the docs changes, mainly about setting up the structure and redirections so far, the new designs will likely be part of the last iteration.

**Comment by oed** [comment]
Structure lgtm. Seems like links top level on reference page (`http://localhost:8000/reference/`) are not working.

**Comment by michaelsena** [comment]
🚀

Michael Sena
CEO and Co-Founder

( https://3box.io )

Visit 3box.io ( http://3box.io ) | Chat with us! ( https://chat.3box.io )

**Pull request merged**
